Injector:
  LoggerBridge:
    class: 'Camspiers\LoggerBridge\LoggerBridge'
    properties:
      BacktraceReporter: '%$LoggerBridgeFilteredBacktraceReporter'
      EnvReporter: '%$LoggerBridgeEnvReporter'
      ErrorReporter: '%$LoggerBridgeWhoopsPrettyErrorReporter'

  LoggerBridgeFilteredBacktraceReporter:
    class: 'Camspiers\LoggerBridge\BacktraceReporter\FilteredBacktraceReporter'
    constructor:
      0:
        - "Camspiers\\LoggerBridge(\\([\w][\w]*))*(?:->)[\w][\w]*"

  LoggerBridgeEnvReporter:
    class: Camspiers\LoggerBridge\EnvReporter\DirectorEnvReporter

  LoggerBridgeWhoopsPrettyHandler:
    class: Whoops\Handler\PrettyPageHandler

  LoggerBridgeWhoopsPrettyErrorReporter:
    class: Camspiers\LoggerBridge\ErrorReporter\WhoopsPrettyErrorReporter
    constructor:
      0: '%$LoggerBridgeWhoopsPrettyHandler'
      1: '%$LoggerBridgeEnvReporter'

  LoggerBridgeDebugErrorReporter:
    class: Camspiers\LoggerBridge\ErrorReporter\DebugErrorReporter
    constructor:
      0: '%$LoggerBridgeEnvReporter'

  RequestProcessor:
    class: RequestProcessor
    properties:
      filters:
        - '%$LoggerBridge'
